version: '3.8'

services:
  payxchangeable:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OCTOPUS_RELEASE_NUMBER=${OCTOPUS_RELEASE_NUMBER:-2.0.0}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - payxchangeable-network

networks:
  payxchangeable-network:
    driver: bridge